spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    #настройки для клиента не активны, тк этот сервис - сервер
    fetch-registry: false
    register-with-eureka: false

